"""
First-run setup wizard — /setup

GET  /setup       Render the configuration form (pre-filled from .env if it exists).
POST /setup/save  Write the submitted values to .env and reload settings.
GET  /setup/done  Confirmation page after successful save.

The setup wizard is only accessible when the platform has not been configured
yet (secret_key is still the default value, or .env does not exist).
Once properly configured, all /setup routes redirect to /.
"""

from __future__ import annotations

import os
import secrets
import base64
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, Form, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates

router = APIRouter(tags=["setup"])

_TEMPLATES = Jinja2Templates(
    directory=str(Path(__file__).parent.parent / "templates")
)

_ENV_PATH = Path(".env")

# The sentinel value that means "not configured yet"
_DEFAULT_SECRET = "changeme-64-char-hex"


def setup_needed() -> bool:
    """Return True if the platform has not been configured yet."""
    from server.config import settings
    return settings.secret_key == _DEFAULT_SECRET or not _ENV_PATH.exists()


def _load_env_values() -> dict[str, str]:
    """
    Parse the current .env file into a plain dict.
    Falls back to .env.example defaults if .env doesn't exist.
    """
    for path in (_ENV_PATH, Path(".env.example")):
        if path.exists():
            values: dict[str, str] = {}
            for line in path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, _, val = line.partition("=")
                    values[key.strip()] = val.strip()
            return values
    return {}


def _write_env(values: dict[str, str]) -> None:
    """
    Write (or overwrite) .env with the provided key-value pairs.
    Keys are sorted into logical groups and written with section headers.
    """
    groups: list[tuple[str, list[str]]] = [
        ("# ---- Required ----------------------------------------", [
            "DKASTLE_ADMIN_USERNAME",
            "DKASTLE_ADMIN_PASSWORD",
            "DKASTLE_SECRET_KEY",
            "DKASTLE_VAULT_KEY",
            "DKASTLE_AUTHORIZED_CIDRS",
        ]),
        ("# ---- Server -------------------------------------------", [
            "DKASTLE_HOST",
            "DKASTLE_PORT",
            "DKASTLE_LOG_LEVEL",
            "DKASTLE_TLS_CERT",
            "DKASTLE_TLS_KEY",
        ]),
        ("# ---- Database -----------------------------------------", [
            "POSTGRES_DB",
            "POSTGRES_USER",
            "POSTGRES_PASSWORD",
            "POSTGRES_HOST",
            "POSTGRES_PORT",
            "DKASTLE_DATABASE_URL",
            "REDIS_URL",
            "DKASTLE_REDIS_URL",
        ]),
        ("# ---- Logging ------------------------------------------", [
            "DKASTLE_LOG_FILE",
            "DKASTLE_GRAYLOG_HOST",
            "DKASTLE_GRAYLOG_PORT",
            "DKASTLE_GRAYLOG_FACILITY",
        ]),
        ("# ---- AI Enrichment ------------------------------------", [
            "DKASTLE_AI_ENABLED",
            "DKASTLE_AI_BACKEND",
            "DKASTLE_OLLAMA_URL",
            "DKASTLE_OLLAMA_MODEL",
            "DKASTLE_ANTHROPIC_API_KEY",
            "DKASTLE_ANTHROPIC_MODEL",
        ]),
        ("# ---- NetBox -------------------------------------------", [
            "DKASTLE_NETBOX_URL",
            "DKASTLE_NETBOX_TOKEN",
            "DKASTLE_NETBOX_SYNC_ENABLED",
        ]),
        ("# ---- Notifications ------------------------------------", [
            "DKASTLE_SMTP_HOST",
            "DKASTLE_SMTP_PORT",
            "DKASTLE_SMTP_USER",
            "DKASTLE_SMTP_PASSWORD",
            "DKASTLE_SMTP_FROM",
            "DKASTLE_SLACK_WEBHOOK_URL",
            "DKASTLE_GENERIC_WEBHOOK_URL",
        ]),
    ]

    written: set[str] = set()
    lines: list[str] = [
        "# ============================================================",
        "# Discoverykastle — Configuration",
        "# Generated by the setup wizard. Edit as needed.",
        "# NEVER commit this file to version control.",
        "# ============================================================",
        "",
    ]

    for header, keys in groups:
        section_lines: list[str] = []
        for key in keys:
            if key in values:
                section_lines.append(f"{key}={values[key]}")
                written.add(key)
        if section_lines:
            lines.append(header)
            lines.extend(section_lines)
            lines.append("")

    # Any leftover keys not in the known groups
    extras = [f"{k}={v}" for k, v in values.items() if k not in written]
    if extras:
        lines.append("# ---- Other -------------------------------------------")
        lines.extend(extras)
        lines.append("")

    _ENV_PATH.write_text("\n".join(lines), encoding="utf-8")


# ──────────────────────────────────────────────────────────────────────────────
# Routes
# ──────────────────────────────────────────────────────────────────────────────

@router.get("/setup", response_class=HTMLResponse)
async def setup_page(request: Request) -> HTMLResponse:
    """Render the setup wizard. Redirect to / if already configured."""
    if not setup_needed():
        return RedirectResponse("/", status_code=302)  # type: ignore[return-value]

    current = _load_env_values()
    return _TEMPLATES.TemplateResponse(
        "setup.html",
        {
            "request": request,
            "v": current,
            "ai_backends": _available_backends(),
        },
    )


@router.post("/setup/save", response_class=HTMLResponse)
async def setup_save(request: Request) -> HTMLResponse:
    """Receive form data, write .env, reload settings, redirect."""
    form = await request.form()
    values: dict[str, str] = {}

    for key, val in form.items():
        if isinstance(val, str):
            values[key.upper()] = val.strip()

    # Auto-generate keys if submitted empty
    if not values.get("DKASTLE_SECRET_KEY") or values["DKASTLE_SECRET_KEY"] == _DEFAULT_SECRET:
        values["DKASTLE_SECRET_KEY"] = secrets.token_hex(32)
    if not values.get("DKASTLE_VAULT_KEY") or values["DKASTLE_VAULT_KEY"] == "changeme-base64-32-bytes":
        values["DKASTLE_VAULT_KEY"] = base64.b64encode(secrets.token_bytes(32)).decode()

    _write_env(values)
    _reload_settings()

    return _TEMPLATES.TemplateResponse(
        "setup.html",
        {
            "request": request,
            "v": values,
            "ai_backends": _available_backends(),
            "saved": True,
        },
    )


@router.get("/setup/generate-key")
async def generate_key(kind: str = "hex") -> dict[str, str]:
    """API endpoint called by the setup form JS to generate secure keys."""
    if kind == "base64":
        return {"key": base64.b64encode(secrets.token_bytes(32)).decode()}
    return {"key": secrets.token_hex(32)}


@router.get("/setup/generate-vapid")
async def generate_vapid() -> dict[str, str]:
    """Generate a new VAPID key pair for Web Push. Returns private + public keys."""
    from server.services.webpush import generate_vapid_keys
    return generate_vapid_keys()


# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

def _reload_settings() -> None:
    """Force pydantic-settings to re-read .env after it has been written."""
    try:
        import importlib
        import server.config as cfg_module
        importlib.reload(cfg_module)
    except Exception:
        pass


def _available_backends() -> list[dict[str, str]]:
    """Return registered backend names and labels for the setup UI."""
    try:
        from server.modules.builtin.ai.backends import REGISTRY
        return [
            {"name": name, "label": cls.label, "requires_key": str(cls.requires_key).lower()}
            for name, cls in REGISTRY.items()
        ]
    except Exception:
        return [
            {"name": "ollama",    "label": "Ollama (local)",    "requires_key": "false"},
            {"name": "anthropic", "label": "Anthropic (cloud)", "requires_key": "true"},
        ]
