"""Sync schema with current models

Revision ID: 4b4c1ae5bfa7
Revises: 0003
Create Date: 2026-06-28 16:58:27.902826

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b4c1ae5bfa7'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('action', sa.String(length=100), nullable=False))
    op.add_column('agent_tasks', sa.Column('operator', sa.String(length=100), nullable=True))
    op.add_column('agent_tasks', sa.Column('attempt', sa.Integer(), nullable=False))
    op.add_column('agent_tasks', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('agent_tasks', sa.Column('timeout_seconds', sa.Integer(), nullable=False))
    op.add_column('agent_tasks', sa.Column('queued_at', sa.DateTime(), nullable=True))
    op.add_column('agent_tasks', sa.Column('dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('agent_tasks', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_agent_tasks_agent_id'), 'agent_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.drop_column('agent_tasks', 'max_retries')
    op.drop_column('agent_tasks', 'retry_count')
    op.drop_column('agent_tasks', 'timeout_at')
    op.drop_column('agent_tasks', 'task_type')
    op.add_column('alerts', sa.Column('source', sa.String(length=100), nullable=False))
    op.add_column('alerts', sa.Column('details', sa.JSON(), nullable=False))
    op.add_column('alerts', sa.Column('acknowledged', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.String(length=100), nullable=True))
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('alerts_host_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_agent_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'title')
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'agent_id')
    op.drop_column('alerts', 'host_id')
    op.add_column('network_devices', sa.Column('host_id', sa.UUID(), nullable=True))
    op.add_column('network_devices', sa.Column('config_snapshot', sa.Text(), nullable=True))
    op.add_column('network_devices', sa.Column('structured_data', sa.Text(), nullable=True))
    op.add_column('network_devices', sa.Column('last_seen', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('network_devices_ip_address_key'), 'network_devices', type_='unique')
    op.drop_constraint(op.f('network_devices_agent_id_fkey'), 'network_devices', type_='foreignkey')
    op.create_foreign_key(None, 'network_devices', 'hosts', ['host_id'], ['id'])
    op.drop_column('network_devices', 'agent_id')
    op.drop_column('network_devices', 'raw_config')
    op.drop_constraint(op.f('uq_services_host_port_proto'), 'services', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(op.f('uq_services_host_port_proto'), 'services', ['host_id', 'port', 'protocol'], postgresql_nulls_not_distinct=False)
    op.add_column('network_devices', sa.Column('raw_config', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('network_devices', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'network_devices', type_='foreignkey')
    op.create_foreign_key(op.f('network_devices_agent_id_fkey'), 'network_devices', 'agents', ['agent_id'], ['id'])
    op.create_unique_constraint(op.f('network_devices_ip_address_key'), 'network_devices', ['ip_address'], postgresql_nulls_not_distinct=False)
    op.drop_column('network_devices', 'last_seen')
    op.drop_column('network_devices', 'structured_data')
    op.drop_column('network_devices', 'config_snapshot')
    op.drop_column('network_devices', 'host_id')
    op.add_column('alerts', sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('alerts_agent_id_fkey'), 'alerts', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('alerts_host_id_fkey'), 'alerts', 'hosts', ['host_id'], ['id'])
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged')
    op.drop_column('alerts', 'details')
    op.drop_column('alerts', 'source')
    op.add_column('agent_tasks', sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('agent_tasks', sa.Column('timeout_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('agent_tasks', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('agent_tasks', sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_id'), table_name='agent_tasks')
    op.drop_column('agent_tasks', 'next_retry_at')
    op.drop_column('agent_tasks', 'dispatched_at')
    op.drop_column('agent_tasks', 'queued_at')
    op.drop_column('agent_tasks', 'timeout_seconds')
    op.drop_column('agent_tasks', 'max_attempts')
    op.drop_column('agent_tasks', 'attempt')
    op.drop_column('agent_tasks', 'operator')
    op.drop_column('agent_tasks', 'action')
    # ### end Alembic commands ###
